# Generated by Django 4.1.6 on 2023-02-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fruit'), (2, 'Vegetable'), (3, 'Pasta'), (4, 'Sauce'), (5, 'Bakery'), (6, 'Cheese'), (7, 'Meat'), (8, 'Sweeteners'), (9, 'Dairy'), (10, 'Seasoning'), (11, 'Cereals'), (12, 'Other')]),
        ),
    ]
